name = "team_fireworks/rocket"
version = "0.1.0"
description = "General-purpose Roblox building plugin"
authors = ["Team Fireworks"]
repository = "https://github.com/team-fireworks/rocket"
license = "MPL-2.0"

[target]
environment = "roblox"

[dependencies]
Charm = { wally = "littensy/charm", version = "^0.11.0-rc.3" }
Iris = { wally = "sirmallard/iris", version = "^2.5.0" }
Promise = { wally = "lukadev-0/typed-promise", version = "^4.0.2" }
Signal = { wally = "data-oriented-house/lemonsignal", version = "^1.11.0" }
Trove = { wally = "sleitnick/trove", version = "^1.8.0" }
typeforge = { wally = "cameronpcampbell/typeforge", version = "^2.1.0" }

[indices]
default = "https://github.com/pesde-pkg/index"

[wally_indices]
default = "https://github.com/UpliftGames/wally-index"

[scripts]
roblox_sync_config_generator = ".pesde/scripts/roblox_sync_config_generator.luau"
sourcemap_generator = ".pesde/scripts/sourcemap_generator.luau"

[dev_dependencies]
scripts = { name = "pesde/scripts_rojo", version = "^0.2.0", target = "lune" }
rojo = { name = "pesde/rojo", version = "^7.5.1", target = "lune" }
pathfs = { name = "jiwonz/pathfs", version = "^0.6.0", target = "lune" }

[engines]
pesde = "^0.7.2"
lune = "^0.10.2"
