# This file lists tools managed by Rokit, a toolchain manager for Roblox projects.
# For more information, see https://github.com/rojo-rbx/rokit

# New tools can be added by running `rokit add <tool>` in a terminal.

[tools]
luau-lsp = "JohnnyMorganz/luau-lsp@1.58.0"
rojo = "rojo-rbx/rojo@7.6.1"
lune = "lune-org/lune@0.10.4"
StyLua = "JohnnyMorganz/StyLua@2.3.1"
darklua = "seaofvoices/darklua@0.17.3"
selene = "Kampfkarren/selene@0.29.0"
